package co.edu.itp.ciecyt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProyectoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAllPropertiesEquals(Proyecto expected, Proyecto actual) {
        assertProyectoAutoGeneratedPropertiesEquals(expected, actual);
        assertProyectoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAllUpdatablePropertiesEquals(Proyecto expected, Proyecto actual) {
        assertProyectoUpdatableFieldsEquals(expected, actual);
        assertProyectoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoAutoGeneratedPropertiesEquals(Proyecto expected, Proyecto actual) {
        assertThat(expected)
            .as("Verify Proyecto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoUpdatableFieldsEquals(Proyecto expected, Proyecto actual) {
        assertThat(expected)
            .as("Verify Proyecto relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProyectoUpdatableRelationshipsEquals(Proyecto expected, Proyecto actual) {}
}
